import { Cpu, GitMerge, Info } from 'lucide-react'

import { ENGINE_VARIANT_VAL_AUROC, TEST_AUROC, TOTAL_WINDOW_FEATURES } from '@/data/modelArtifacts'

export function ModelRelationship() {
  return (
    <section className="wx-panel" aria-labelledby="explain-relationship-title">
      <div className="wx-panel-head">
        <span className="wx-mono" id="explain-relationship-title">
          Model relationship
        </span>
        <span className="wx-mono">deployed vs eval-side</span>
      </div>

      <div className="wx-panel-body" style={{ display: 'grid', gap: 14 }}>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
            gap: 12,
          }}
        >
          <div
            style={{
              border: '1px solid var(--c-line)',
              borderRadius: 11,
              padding: 14,
              background: 'var(--c-surface)',
            }}
          >
            <div
              style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}
            >
              <Cpu size={15} aria-hidden="true" style={{ color: 'var(--c-accent)' }} />
              <span style={{ fontSize: 13, fontWeight: 700 }}>Deployed · engine model</span>
              <span className="wx-pill wx-mono tone-info">runs in the app</span>
            </div>
            <p
              style={{ margin: 0, fontSize: 12, lineHeight: 1.6, color: 'var(--c-text-sub)' }}
            >
              XGBoost on the {TOTAL_WINDOW_FEATURES} window features — CPU-cheap and natively
              TreeSHAP-explainable. This is what actually scores a capture in the app.
            </p>
            <div className="wx-kv wx-mono" style={{ marginTop: 10 }}>
              <dt>xgb test AUROC</dt>
              <dd className="wx-num">{TEST_AUROC.xgb.toFixed(3)}</dd>
            </div>
          </div>

          <div
            style={{
              border: '1px solid var(--c-line)',
              borderRadius: 11,
              padding: 14,
              background: 'var(--c-surface)',
            }}
          >
            <div
              style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}
            >
              <GitMerge size={15} aria-hidden="true" style={{ color: 'var(--c-text-muted)' }} />
              <span style={{ fontSize: 13, fontWeight: 700 }}>Eval-side · fused</span>
              <span className="wx-pill wx-mono">headline only</span>
            </div>
            <p
              style={{ margin: 0, fontSize: 12, lineHeight: 1.6, color: 'var(--c-text-sub)' }}
            >
              Rank-mean of the TGN encoder and XGBoost — parameter-free, regenerated by{' '}
              <code>scripts/make_ablation_table.py</code>. This produces the published headline.
            </p>
            <div className="wx-kv wx-mono" style={{ marginTop: 10 }}>
              <dt>fused test AUROC</dt>
              <dd className="wx-num">{TEST_AUROC.fused.toFixed(3)}</dd>
            </div>
          </div>
        </div>

        <div>
          <div className="wx-mono" style={{ marginBottom: 8, color: 'var(--c-text-muted)' }}>
            Engine variants · matched validation split
          </div>
          <dl style={{ margin: 0 }}>
            <div className="wx-kv wx-mono">
              <dt>flow-only (CSV path) AUROC</dt>
              <dd className="wx-num">{ENGINE_VARIANT_VAL_AUROC.flowOnly.toFixed(3)}</dd>
            </div>
            <div className="wx-kv wx-mono">
              <dt>full 30-feature (PCAP path) AUROC</dt>
              <dd className="wx-num">{ENGINE_VARIANT_VAL_AUROC.full.toFixed(3)}</dd>
            </div>
          </dl>
        </div>

        <div className="wx-notice tone-warn" role="note">
          <Info size={15} aria-hidden="true" />
          <div>
            Engine-side fusion is roadmap — the app does <strong>not</strong> run the TGN encoder;
            it scores with the XGBoost engine model alone. Test-split AUROC (1% FPR budget) is sourced
            from the <code>README.md</code> ablation table, generated by <code>eval/ablation.py</code>{' '}
            from <code>results/*.json</code>. The matched validation-split variant figures are from{' '}
            <code>docs/limitations.md</code> section 3 (from <code>artifacts/engine_threshold.json</code>).
          </div>
        </div>
      </div>
    </section>
  )
}
