/**
 * Model transparency constants for the /explain console (page 6).
 *
 * Every value in this file is transcribed verbatim from a real project
 * artifact or document. The source path is cited beside each block. Nothing
 * here is computed, rounded at rest, or invented — display rounding happens in
 * the components. This module is the frontend's single copy of these figures so
 * the /explain page never hand-enters a number inline.
 */

import type { AttackStage } from '@/types/backend'

/* ------------------------------------------------------------------ */
/* Global feature importance                                           */
/* ------------------------------------------------------------------ */

export interface ShapFeatureImportance {
  /** Real named window feature (never an embedding index). */
  feature: string
  /** Mean |SHAP| value over the XGBoost model. */
  meanAbsShap: number
}

/**
 * Mean |SHAP| over the XGBoost fast-tier model, top 10 of 30 window features.
 * Source: diagnostics/shap_xgb_top10.json — values are copied exactly.
 *
 * The values are carried as string literals so the full precision of the
 * source file is preserved verbatim in this module (a bare number literal at
 * that precision trips `no-loss-of-precision`); they are parsed to `number`
 * once for the chart, which only ever displays them to 3 decimals.
 */
const SHAP_XGB_TOP10_SOURCE: ReadonlyArray<readonly [string, string]> = [
  ['ttl_mean', '3.389704704284668'],
  ['payload_hist_0', '3.2296411991119385'],
  ['tcp_win_var', '1.6667556762695312'],
  ['sent_bytes', '1.495546817779541'],
  ['internal', '1.4036058187484741'],
  ['sent_pkts', '1.3811544179916382'],
  ['tcp_win_mean', '1.1069011688232422'],
  ['server_port_ratio', '0.9379857778549194'],
  ['net24_bucket', '0.8920385837554932'],
  ['syn', '0.8516531586647034'],
]

export const SHAP_XGB_TOP10: ShapFeatureImportance[] = SHAP_XGB_TOP10_SOURCE.map(
  ([feature, value]) => ({ feature, meanAbsShap: Number.parseFloat(value) }),
)

/** Total window features per (source host, 15 s window). Source: data/windows.py. */
export const TOTAL_WINDOW_FEATURES = 30

/* ------------------------------------------------------------------ */
/* Model relationship — AUROC figures                                  */
/* ------------------------------------------------------------------ */

/**
 * Test-split AUROC (operating point = 1% FPR budget).
 * Source: README.md ablation table, generated by eval/ablation.py from
 * results/*.json.
 */
export const TEST_AUROC = {
  xgb: 0.872,
  fused: 0.933,
} as const

/**
 * Matched validation-split AUROC for the two engine variants.
 * Source: docs/limitations.md section 3, from artifacts/engine_threshold.json.
 */
export const ENGINE_VARIANT_VAL_AUROC = {
  /** flow-only model (CSV path). */
  flowOnly: 0.847,
  /** full 30-feature model (PCAP path). */
  full: 0.806,
} as const

/* ------------------------------------------------------------------ */
/* MITRE technique map                                                 */
/* ------------------------------------------------------------------ */

export interface TechniqueRule {
  /** Human-readable rule condition, or null for the stage default. */
  condition: string | null
  technique: string | null
  techniqueName: string
  /** Optional qualifier shown after the name. */
  note?: string
}

export interface StageTechniqueMap {
  stage: AttackStage
  rules: TechniqueRule[]
}

/**
 * Transcribed verbatim from engine/technique_map.yaml. The first matching rule
 * per stage wins; only techniques whose evidence exists in the features are
 * mapped. A stage with no default maps to no technique.
 */
export const TECHNIQUE_MAP: StageTechniqueMap[] = [
  {
    stage: 'benign',
    rules: [{ condition: null, technique: null, techniqueName: 'No technique' }],
  },
  {
    stage: 'recon',
    rules: [
      { condition: null, technique: 'T1046', techniqueName: 'Network Service Discovery' },
      {
        condition: 'distinct_dst_ips > 20',
        technique: 'T1046',
        techniqueName: 'Network Service Discovery',
      },
      {
        condition: 'sequential_port_ratio > 0.5',
        technique: 'T1046',
        techniqueName: 'Network Service Discovery',
        note: 'sequential port sweep',
      },
    ],
  },
  {
    stage: 'initial_access',
    rules: [
      { condition: null, technique: 'T1110', techniqueName: 'Brute Force' },
      {
        condition: 'syn > 50',
        technique: 'T1110',
        techniqueName: 'Brute Force',
        note: 'credential guessing',
      },
    ],
  },
  {
    stage: 'lateral_movement',
    rules: [
      { condition: null, technique: 'T1021', techniqueName: 'Remote Services' },
      {
        condition: 'distinct_dst_ports > 20',
        technique: 'T1046',
        techniqueName: 'Network Service Discovery',
        note: 'internal sweep',
      },
      {
        condition: 'sequential_port_ratio > 0.5',
        technique: 'T1046',
        techniqueName: 'Network Service Discovery',
        note: 'internal sequential sweep',
      },
    ],
  },
  {
    stage: 'c2',
    rules: [{ condition: null, technique: 'T1071', techniqueName: 'Application Layer Protocol' }],
  },
  {
    stage: 'exfiltration',
    rules: [
      { condition: null, technique: 'T1041', techniqueName: 'Exfiltration Over C2 Channel' },
      {
        condition: 'sent_bytes > 50000',
        technique: 'T1048',
        techniqueName: 'Exfiltration Over Alternative Protocol',
        note: 'large outbound transfer',
      },
    ],
  },
  {
    stage: 'impact',
    rules: [{ condition: null, technique: 'T1498', techniqueName: 'Network Denial of Service' }],
  },
]

/* ------------------------------------------------------------------ */
/* Stage training coverage                                             */
/* ------------------------------------------------------------------ */

export type CoverageLevel = 'covered' | 'none' | 'zero_windows'

export interface StageCoverage {
  stage: AttackStage
  level: CoverageLevel
  detail: string
}

/**
 * Per-stage training coverage.
 * Source: docs/limitations.md sections 1-2 and docs/stage_mapping.md.
 */
export const STAGE_COVERAGE: StageCoverage[] = [
  { stage: 'benign', level: 'covered', detail: 'Covered in the training split.' },
  {
    stage: 'recon',
    level: 'none',
    detail: 'No training coverage.',
  },
  {
    stage: 'initial_access',
    level: 'covered',
    detail: 'Covered — bruteforce family in train.',
  },
  {
    stage: 'lateral_movement',
    level: 'zero_windows',
    detail: 'ZERO labelled windows across train / val / test.',
  },
  {
    stage: 'c2',
    level: 'none',
    detail:
      'Never appears in the training split, so the stage head cannot be expected to emit it.',
  },
  {
    stage: 'exfiltration',
    level: 'zero_windows',
    detail: 'ZERO labelled windows across train / val / test.',
  },
  {
    stage: 'impact',
    level: 'covered',
    detail: 'Covered — DoS / DDoS family in train.',
  },
]

/**
 * The consequence of the coverage gaps, stated verbatim in substance.
 * Source: docs/limitations.md sections 1-2.
 */
export const STAGE_COVERAGE_CONSEQUENCE =
  'The shipped system forecasts a binary infiltration probability and assigns a stage ' +
  'from interpretable named-feature rules; it is NOT a validated 7-class classifier.'

/* ------------------------------------------------------------------ */
/* Limitations & confidence                                            */
/* ------------------------------------------------------------------ */

export type LimitationTone = 'warn' | 'danger'

export interface Limitation {
  title: string
  body: string
  tone: LimitationTone
  /** Repository documents the limitation is drawn from. */
  sources: string[]
}

/**
 * First-class documented limitations.
 * Sources: docs/limitations.md, README.md, tier1_hardening_report.md.
 */
export const LIMITATIONS: Limitation[] = [
  {
    title: 'n = 2 episodes, one attacker host',
    body:
      'The headline rests on n = 2 attack episodes, and both are two sessions of the same ' +
      'attacker host — so there is no confidence interval.',
    tone: 'danger',
    sources: ['README.md', 'docs/limitations.md'],
  },
  {
    title: 'Detection carried by XGBoost',
    body:
      'Detection is dominated by the XGBoost member of the fusion rather than the novel ' +
      'temporal-graph (TGN) component.',
    tone: 'warn',
    sources: ['README.md', 'tier1_hardening_report.md'],
  },
  {
    title: 'Evaluation-row multiplicity inflates metrics',
    body:
      'AUROC / F1 are inflated by evaluation-row multiplicity. De-duplicated, the fused model ' +
      'reads AUROC 0.89 and F1 0.04, while lead time and 2/2 episodes are unchanged.',
    tone: 'warn',
    sources: ['tier1_hardening_report.md', 'README.md'],
  },
  {
    title: 'Two of seven stages have no training data',
    body:
      'Two of the seven stages (lateral_movement, exfiltration) have no training data at all — ' +
      'zero labelled windows across train / val / test.',
    tone: 'danger',
    sources: ['docs/limitations.md'],
  },
  {
    title: 'Cross-family generalisation test',
    body:
      'Splits are attack-family-disjoint (train = bruteforce + DoS, test = bot), so the headline ' +
      'is a cross-family generalisation test, not an in-distribution score.',
    tone: 'warn',
    sources: ['docs/benchmark_protocol.md', 'README.md'],
  },
  {
    title: 'CSV cannot carry packet features',
    body:
      'A flow CSV physically cannot carry packet-statistic features, so the flow-only engine ' +
      'variant scores captures without them.',
    tone: 'warn',
    sources: ['docs/limitations.md'],
  },
  {
    title: 'World model failed its gate; k-step is ranking only',
    body:
      'The RSSM world model failed its acceptance gate (0/2 episodes, 0 s lead) and is recorded ' +
      'as a negative result. The shipped k-step head is a ranking capability whose 1% operating ' +
      'point does not fire.',
    tone: 'danger',
    sources: ['docs/decisions/', 'README.md'],
  },
  {
    title: 'Benign traffic is subsampled',
    body:
      'Benign traffic is subsampled to about 30 of about 450 hosts per day, so alerts/day is a ' +
      'within-sample extrapolation.',
    tone: 'warn',
    sources: ['docs/limitations.md'],
  },
  {
    title: 'k=1 and k=2 are near-nowcasts',
    body:
      'Overlapping 15 s windows on a 5 s stride mean the k=1 and k=2 forecast horizons are ' +
      'near-nowcasts.',
    tone: 'warn',
    sources: ['docs/limitations.md'],
  },
  {
    title: 'Known dataset label errors',
    body: 'The CSE-CIC-IDS2018 dataset has known label errors.',
    tone: 'warn',
    sources: ['docs/limitations.md'],
  },
  {
    title: 'Ledger is tamper-evident, not a blockchain',
    body:
      'The audit ledger is tamper-evident (hash chain + Merkle roots), not a distributed ' +
      'blockchain.',
    tone: 'warn',
    sources: ['docs/limitations.md', 'README.md'],
  },
]
