/**
 * projectResults.ts — committed, source-cited project results.
 *
 * These are the ONLY numbers the /forecast and /benchmark evidence pages may
 * render. Every block below carries a source comment. Nothing here is derived
 * from a live analysis session; these are the reproducible project results as
 * published in this checkout. Where a per-horizon value is not published in
 * this checkout it is represented as `null` and MUST be rendered as
 * "not published in this checkout" — never interpolated or invented.
 *
 * PROVENANCE CHAIN (source: docs/benchmark_protocol.md, README.md):
 *   results/*.json
 *     -> eval/ablation.py
 *     -> scripts/make_ablation_table.py --budget 0.01
 *     -> README.md ablation table
 *   per-horizon:   results/forecast.json  (NOT committed in this checkout —
 *                  results and weights are gitignored, which is exactly why
 *                  most horizons are unpublished here)
 *   thresholds:    artifacts/engine_threshold.json (selected on validation
 *                  split at a fixed FPR budget; never a literal in code)
 *   regeneration:  `python -m eval.harness` (harness),
 *                  `python scripts/make_ablation_table.py --budget 0.01` (table)
 */

/* ------------------------------------------------------------------ */
/* Model comparison — transcribed EXACTLY from README.md              */
/* Source: README.md → Results table. Test split 02-03 Bot,           */
/* operating point = 1% FPR budget. Generated by eval/ablation.py     */
/* from results/*.json via scripts/make_ablation_table.py --budget 0.01 */
/* ------------------------------------------------------------------ */

export type ModelKind = 'headline' | 'baseline' | 'standard'

export interface BenchmarkRow {
  model: string
  f1: number
  precision: number
  recall: number
  auroc: number
  ece: number
  leadMedianS: number
  leadIqrS: string
  episodes: string
  alertsPerHostDay: number
  /** headline = shipped fused model; baseline = PS-graded LR baseline */
  kind: ModelKind
}

export const BENCHMARK_SOURCE = 'README.md → Results (eval/ablation.py · budget 0.01)'

export const BENCHMARK_ROWS: BenchmarkRow[] = [
  {
    model: 'fused',
    f1: 0.172,
    precision: 0.268,
    recall: 0.127,
    auroc: 0.933,
    ece: 0.021,
    leadMedianS: 4195.0,
    leadIqrS: '3568-4822',
    episodes: '2/2',
    alertsPerHostDay: 187.1,
    kind: 'headline',
  },
  {
    model: 'xgb',
    f1: 0.14,
    precision: 0.183,
    recall: 0.114,
    auroc: 0.872,
    ece: 0.022,
    leadMedianS: 4208.0,
    leadIqrS: '3581-4834',
    episodes: '2/2',
    alertsPerHostDay: 246.6,
    kind: 'standard',
  },
  {
    model: 'tgn',
    f1: 0.009,
    precision: 0.033,
    recall: 0.005,
    auroc: 0.84,
    ece: 0.042,
    leadMedianS: 38.0,
    leadIqrS: '19-56',
    episodes: '1/2',
    alertsPerHostDay: 65.1,
    kind: 'standard',
  },
  {
    model: 'lstm',
    f1: 0.015,
    precision: 0.029,
    recall: 0.01,
    auroc: 0.764,
    ece: 0.023,
    leadMedianS: 4202.0,
    leadIqrS: '3579-4826',
    episodes: '2/2',
    alertsPerHostDay: 145.3,
    kind: 'standard',
  },
  {
    model: 'tgn_graft',
    f1: 0.013,
    precision: 0.023,
    recall: 0.009,
    auroc: 0.701,
    ece: 0.023,
    leadMedianS: 1035.0,
    leadIqrS: '935-1135',
    episodes: '2/2',
    alertsPerHostDay: 161.3,
    kind: 'standard',
  },
  {
    model: 'tgn_graft_no_time2vec',
    f1: 0.013,
    precision: 0.023,
    recall: 0.009,
    auroc: 0.701,
    ece: 0.023,
    leadMedianS: 1035.0,
    leadIqrS: '935-1135',
    episodes: '2/2',
    alertsPerHostDay: 161.3,
    kind: 'standard',
  },
  {
    model: 'lr',
    f1: 0.001,
    precision: 0.002,
    recall: 0.001,
    auroc: 0.573,
    ece: 0.026,
    leadMedianS: 0.0,
    leadIqrS: '0-0',
    episodes: '0/2',
    alertsPerHostDay: 112.3,
    kind: 'baseline',
  },
  {
    model: 'tgn_graft_t2v_clamped',
    f1: 0.014,
    precision: 0.024,
    recall: 0.01,
    auroc: 0.38,
    ece: 0.023,
    leadMedianS: 30.0,
    leadIqrS: '15-45',
    episodes: '1/2',
    alertsPerHostDay: 156.9,
    kind: 'standard',
  },
]

/* ------------------------------------------------------------------ */
/* Forecast horizons — k-step head, presented as a RANKING capability */
/* Source: README.md (M7 forecast row), docs/limitations.md.          */
/* Window 15 s, stride 5 s ⇒ k windows ahead = 5·k seconds ahead.     */
/* Published per-horizon test AUROC in this checkout: k=4 ≈ 0.84,     */
/* k=8 = 0.890. NOTHING is published for k=1,2,3,5,6,7 in this        */
/* checkout (results/forecast.json is gitignored) ⇒ auroc: null.      */
/* ------------------------------------------------------------------ */

export const FORECAST_SOURCE =
  'README.md (M7) + docs/limitations.md · per-horizon results/forecast.json (not committed)'

/** Window / stride definition (source: docs/product.md, README.md M3/M7). */
export const WINDOW_SECONDS = 15
export const STRIDE_SECONDS = 5

export type HorizonNote = 'near-nowcast' | 'honest horizon' | 'threshold stops transferring'

export interface HorizonRow {
  k: number
  secondsAhead: number
  /** null ⇒ "not published in this checkout"; approx flags the ≈ 0.84 value */
  auroc: number | null
  aurocApprox: boolean
  note: HorizonNote
}

export const HORIZON_ROWS: HorizonRow[] = [
  { k: 1, secondsAhead: 5, auroc: null, aurocApprox: false, note: 'near-nowcast' },
  { k: 2, secondsAhead: 10, auroc: null, aurocApprox: false, note: 'near-nowcast' },
  { k: 3, secondsAhead: 15, auroc: null, aurocApprox: false, note: 'honest horizon' },
  { k: 4, secondsAhead: 20, auroc: 0.84, aurocApprox: true, note: 'honest horizon' },
  { k: 5, secondsAhead: 25, auroc: null, aurocApprox: false, note: 'honest horizon' },
  { k: 6, secondsAhead: 30, auroc: null, aurocApprox: false, note: 'honest horizon' },
  { k: 7, secondsAhead: 35, auroc: null, aurocApprox: false, note: 'honest horizon' },
  {
    k: 8,
    secondsAhead: 40,
    auroc: 0.89,
    aurocApprox: false,
    note: 'threshold stops transferring',
  },
]

/**
 * The fixed-budget operating point of the k-step head does NOT fire.
 * Source: README.md (M7 row: "operating point 0/2 at the 1% budget"),
 * docs/limitations.md. Documented as a RANKING limit, not a recalibratable
 * threshold — an oracle check confirmed it; seed-averaging on GPU is the
 * documented path to recover a forward operating point.
 */
export const KSTEP_OPERATING_POINT = {
  model: 'k-step head',
  budget: '1% FPR',
  f1: '≤ 0.009',
  episodes: '0/2',
  leadSeconds: 0,
  detail:
    'Documented as a ranking limit, not a recalibratable threshold — an oracle check confirmed it. Seed-averaging on GPU is the documented path to recover a forward operating point.',
} as const

/**
 * The shipped early warning is produced by the HORIZON-0 fused model, NOT the
 * k-step head. This is precursor detection by the horizon-0 model.
 * Source: README.md (headline / Results), docs/limitations.md.
 */
export const HORIZON0_FUSED_LEAD = {
  model: 'horizon-0 fused',
  budget: '1% FPR',
  episodes: '2/2',
  leadMedianText: '≈ 70 min (median)',
  leadMedianSeconds: 4195.0, // README fused lead_median_s
  perEpisodeText: '≈ 49 min and ≈ 91 min before completion',
  detail:
    'Precursor detection by the horizon-0 fused model at the 1% budget — this is the shipped early warning, not the k-step head.',
} as const

/* ------------------------------------------------------------------ */
/* Operating point / thresholding                                      */
/* Source: docs/limitations.md §3, README.md, docs/benchmark_protocol.md */
/* ------------------------------------------------------------------ */

export const OPERATING_POINT = {
  thresholdSource: 'artifacts/engine_threshold.json',
  detail:
    'Threshold is selected on the validation split at a fixed FPR budget (0.1% or 1% of host-windows) and persisted to artifacts/engine_threshold.json; it is never a literal in code.',
  /** Validation AUROC of the deployed engine variants (docs/limitations.md §3). */
  valAurocFlowOnly: 0.847,
  valAurocFull: 0.806,
  splits:
    'Splits are attack-family-disjoint: train = bruteforce+DoS, val = infiltration, test = bot.',
} as const

/* ------------------------------------------------------------------ */
/* Ablation findings (source: README.md, tier1_hardening_report.md)    */
/* ------------------------------------------------------------------ */

export const ABLATION_FINDINGS: string[] = [
  'tgn_graft and tgn_graft_no_time2vec are the SAME configuration and now produce bit-identical rows — that identity is the determinism proof. Before the determinism fix those two runs read 0.853 vs 0.923. (Time2Vec was ablated OFF.)',
  'tgn_graft_t2v_clamped collapses to AUROC 0.380 under enforced determinism after reading 0.937 as a nondeterministic draw — which vindicates the decision not to promote it on a test-set win.',
  "The fusion's members have nearly uncorrelated errors: when the determinism fix cost the TGN encoder 0.037 AUROC, the fused headline moved only −0.009 (0.942 → 0.933) while single-model rows swung by up to 0.56.",
]

export const ABLATION_SOURCE = 'README.md + tier1_hardening_report.md'

/* ------------------------------------------------------------------ */
/* Evidence provenance (source: README.md, docs/benchmark_protocol.md) */
/* ------------------------------------------------------------------ */

export const EVIDENCE_STEPS: string[] = [
  'results/*.json → eval/ablation.py → scripts/make_ablation_table.py --budget 0.01 → README.md',
  'Per-horizon AUROC from results/forecast.json (not committed in this checkout).',
  'Thresholds from artifacts/engine_threshold.json — selected on validation, never a literal in code.',
  'Protocol documented in docs/benchmark_protocol.md; regenerate the harness with `python -m eval.harness`.',
  'Every torch-trained row was regenerated under enforced training determinism; repeated runs are bit-identical.',
]

/* ------------------------------------------------------------------ */
/* Limitations (source: README.md, docs/limitations.md,               */
/* tier1_hardening_report.md → Limitations & Confidence)               */
/* ------------------------------------------------------------------ */

export const LIMITATIONS: string[] = [
  'n = 2 episodes, and both are two sessions of the same attacker host — so there is no confidence interval.',
  'Detection is dominated by XGBoost rather than the novel temporal-graph component.',
  'Evaluation-row multiplicity inflates AUROC/F1: de-duplicated, the fused model reads AUROC 0.89 and F1 0.04 — lead time and 2/2 unchanged.',
  'lateral_movement and exfiltration have zero labelled windows; c2 never appears in the training split.',
  'Benign hosts are subsampled to ≈ 30 of ≈ 450 per day, so alerts/day is a within-sample extrapolation.',
  'The dataset (CSE-CIC-IDS2018) has known label errors.',
  "The k-step head's fixed-budget operating point does not fire (F1 ≤ 0.009, 0/2 episodes at the 1% budget).",
  'The ledger is tamper-evident, not a distributed blockchain.',
  'Validation is the near-silent infiltration day and is harder for every model — an honest asymmetry, not uniform inflation.',
]

export const LIMITATIONS_SOURCE =
  'README.md + docs/limitations.md + tier1_hardening_report.md → Limitations & Confidence'
